

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Documents {
                ref class Run;
            }
        }
    }
}

namespace CPPSample
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Button^ TimelineBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ MsgWithPicBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ NoPicPostBtn;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ statusTBK;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ resultTBK;
        private: ::Windows::UI::Xaml::Documents::Run^ ResultRun;
        private: ::Windows::UI::Xaml::Documents::Run^ statusRun;
    };
}

